# Ask a built backend library which parts of the contract it actually defines,
# and write the answer out as a header of 0/1 macros.
#
# Why not a link test: every operation in `unibind/detail/backend.h` is declared by
# the public headers whatever the backend does, so a missing one compiles
# cleanly and fails at link. A suite that called it would not build at all -
# which is the opposite of "skipped and reported as skipped". The archive's
# symbol names are the one place the truth is written down without asking the
# backend to maintain a list of its own.
#
# The scan reads the mangled names out of the archive: MSVC's `?Name@Scope@ub@@`
# and, so that a non-MSVC toolchain would work too, the Itanium
# `_ZN2ub<len>Scope<len>Name` spelling.
#
#   cmake -DUNIBIND_PROBE_LIB=... -DUNIBIND_PROBE_OUT=... -DUNIBIND_PROBE_BACKEND=...
#         -DUNIBIND_PROBE_TABLE=... -P ProbeCapabilities.cmake

cmake_minimum_required(VERSION 3.25)

foreach(required UNIBIND_PROBE_LIB UNIBIND_PROBE_OUT UNIBIND_PROBE_BACKEND UNIBIND_PROBE_TABLE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "ProbeCapabilities: ${required} is not set")
    endif()
endforeach()

if(NOT EXISTS "${UNIBIND_PROBE_LIB}")
    message(FATAL_ERROR "ProbeCapabilities: no backend library at '${UNIBIND_PROBE_LIB}'")
endif()

include("${UNIBIND_PROBE_TABLE}")

# The archive's symbol index - its first member - lists exactly the symbols the
# archive *defines*, which is why the scan is bounded to it. See ArchiveIndex.cmake.
include("${CMAKE_CURRENT_LIST_DIR}/ArchiveIndex.cmake")

unibind_archive_index_end("${UNIBIND_PROBE_LIB}" indexEnd)
if(indexEnd EQUAL 0)
    message(FATAL_ERROR
        "ProbeCapabilities: '${UNIBIND_PROBE_LIB}' is not an archive with a symbol index, so what it "
        "defines cannot be told apart from what it merely mentions.")
endif()

file(STRINGS "${UNIBIND_PROBE_LIB}" mangled LIMIT_INPUT ${indexEnd}
     REGEX "([?][A-Za-z_][A-Za-z0-9_]*@[A-Za-z_][A-Za-z0-9_]*@ub@@)|(_ZN2ub[0-9])")
string(JOIN "\n" symbols ${mangled})

# True when the backend defines `name` in `ub::scope`.
function(unibind_defines name scope out)
    set(found FALSE)
    if(symbols MATCHES "[?]${name}@${scope}@ub@@")
        set(found TRUE)
    else()
        string(LENGTH "${scope}" scopeLen)
        string(LENGTH "${name}" nameLen)
        if(symbols MATCHES "_ZN2ub${scopeLen}${scope}${nameLen}${name}[EIv]")
            set(found TRUE)
        endif()
    endif()
    set(${out} ${found} PARENT_SCOPE)
endfunction()

set(lines "")
set(present "")
set(absent "")

foreach(row IN LISTS UNIBIND_CAPABILITIES)
    string(REPLACE "|" ";" parts "${row}")
    list(GET parts 0 capability)
    list(GET parts 1 wanted)
    string(REPLACE "," ";" wanted "${wanted}")

    set(have 1)
    set(missing "")
    foreach(entry IN LISTS wanted)
        if(entry MATCHES "^([A-Za-z0-9_]+)@([A-Za-z0-9_]+)$")
            set(name "${CMAKE_MATCH_1}")
            set(scope "${CMAKE_MATCH_2}")
        else()
            set(name "${entry}")
            set(scope "detail")
        endif()
        unibind_defines("${name}" "${scope}" defined)
        if(NOT defined)
            set(have 0)
            list(APPEND missing "${scope}::${name}")
        endif()
    endforeach()

    if(have)
        list(APPEND present "${capability}")
        list(APPEND lines "#define UNIBIND_TEST_HAS_${capability} 1")
    else()
        list(APPEND absent "${capability}")
        list(JOIN missing ", " missingText)
        list(APPEND lines "// missing: ${missingText}")
        list(APPEND lines "#define UNIBIND_TEST_HAS_${capability} 0")
    endif()
endforeach()

list(JOIN lines "\n" body)
list(JOIN present " " presentText)
list(JOIN absent " " absentText)

set(generated
"#pragma once
// Generated by tests/cmake/ProbeCapabilities.cmake from the built backend
// library - do not edit. See tests/README.md.
//
// backend: ${UNIBIND_PROBE_BACKEND}

#define UNIBIND_TEST_BACKEND \"${UNIBIND_PROBE_BACKEND}\"
#define UNIBIND_TEST_CAPABILITIES_PRESENT \"${presentText}\"
#define UNIBIND_TEST_CAPABILITIES_ABSENT \"${absentText}\"

${body}
")

set(existing "")
if(EXISTS "${UNIBIND_PROBE_OUT}")
    file(READ "${UNIBIND_PROBE_OUT}" existing)
endif()
if(NOT existing STREQUAL generated)
    file(WRITE "${UNIBIND_PROBE_OUT}" "${generated}")
else()
    # Unchanged, but the build needs the output to be newer than the library it
    # was derived from or it will run this again on every build.
    file(TOUCH "${UNIBIND_PROBE_OUT}")
endif()

message(STATUS "unibind tests: ${UNIBIND_PROBE_BACKEND} provides [${presentText}]")
if(absent)
    message(STATUS "unibind tests: ${UNIBIND_PROBE_BACKEND} lacks    [${absentText}] - those cases report as skipped")
endif()
